# Generated by Django 3.2.18 on 2023-04-16 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20230413_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='orderStatus',
            field=models.CharField(choices=[('Food is being prepared', 'Food is being prepared'), ('In delivery', 'In delivery'), ('Delivered', 'Delivered')], default='Food is being prepared', max_length=30),
        ),
        migrations.AlterField(
            model_name='foodpackage',
            name='FoodIteminPackage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.fooditem'),
        ),
    ]
